### ISSUE TITLE
Allow empty with collection and Scheme argument doesn't work.

### ISSUE THREAD

**Issue by SleeplessByte** [SleeplessByte/media-types-ruby#17]
[`application/vnd.trailervote.feedback.collection.v1+json`](https://github.com/TrailerVote/trailervote-media-types/blob/master/ruby/lib/trailer_vote/media_types/feedback.rb#L30) doesn't allow empty.

Check `collection` in combination with a `Scheme` and `allow_empty`.

**Comment by thexa4** [comment]
Failing test case:

      class CollectionSchemeTypeEmpty
        include MediaTypes::Dsl

        def self.base_format
          'application/vnd.trailervote.test'
        end

        media_type 'test'

        scheme = MediaTypes::Scheme.new(expected_type: Array) do
          attribute :bar, Numeric
        end

        validations do
          collection :foo, scheme, allow_empty: true
        end
      end

      def test_empty_collection_from_scheme
        assert CollectionSchemeType.validatable?(CollectionSchemeType.to_constructable),
               'Expected media type to be validatable'
        assert CollectionSchemeType.validate!(foo: []), 'Expected input to be valid'
      end

**Comment by SleeplessByte** [comment]
Perfect! Thanks.

**Comment by SleeplessByte** [comment]
Fixed by https://github.com/SleeplessByte/media-types-ruby/pull/36
