### ISSUE TITLE
Link method breaks tests for create view

### ISSUE THREAD

**Issue by karensg** [SleeplessByte/media-types-ruby#47]
Windows, ruby 2.6
Works:
```
        attribute :_links do
          attribute :product_asset do
            attribute :href, Types::HttpUrl
          end
          attribute :action do
            attribute :href, Types::HttpUrl
          end
        end
```
Does not work:
```
link :product_asset 
link :action
```

Tests give an error:
MiniTestError: StackTrace too long

Functionality-wise they both work

**Comment by SleeplessByte** [comment]
Does this test fail for you: https://github.com/SleeplessByte/media-types-ruby/blob/e6ac2b461cdcee143be68c4e8948565b14622c5a/test/media_types/dsl/link_test.rb ?

**Comment by karensg** [comment]
No, it works (had to update to `unf_ext (0.0.7.6)`) in order to run it on 2.6
I guess there might be difference between _links in views and just attributes

**Comment by SleeplessByte** [comment]
There shouldn't be.

Do you have a full media type that fails? I'll look into it and see if we can have it fixed.

**Comment by karensg** [comment]
Okay, indeed. Weird, now it works.. No idea what changed exactly. Thanks!
https://github.com/TrailerVote/trailervote-media-types/pull/54/commits/b63b27af52881706bc2cdbde84b2c67d5a5df6c3
